### ISSUE TITLE
I see that thermos isnt compatible with particlenativeAPI but is Cauldron?

### ISSUE THREAD

**Issue by Zomboos** [Fierioziy/ParticleNativeAPI#5]
Im making a magic plugin for a modded server, but as i see in the issues its having hte same issue im having with thermos. is cauldron compatible with particlenativeAPI?

**Comment by Fierioziy** [comment]
Hi!

Currently this API supports only `vanilla-based Bukkit/Spigot` servers.
If there are forks that are based on them, then they (probably) should works with this API as well (for example `PaperSpigot`).

Answering, there are few issues when it comes to supporting `Forge-based Bukkit/Spigot` servers:
- `Forge` internals (classes that determines `Bukkit` API implementation) differs quite significantly compared to `vanilla` internals.
**This is basically main issue why there are currently no other APIs supporting them**
- particle names (and some of their classes) differs in different way between versions in `vanilla` and `Forge` and it's harder to follow changes in them in `Forge`

Currently i didn't have much time to mess around that much due to studies/work (i would have to deeply analyze `Forge` between many versions & prepare ASM stuff for that and it takes MUCH time).

**I'll try to dig into it around June/July i think.** I'll make an issue TODO for that.

**Comment by Fierioziy** [comment]
Hi, I'm closing it in favor of [this issue](https://github.com/Fierioziy/ParticleNativeAPI/issues/6) which is very related to this issue.

I suggest subscribing to notifications on this linked issue for further updates
